[2025-09-11T03:51:08.046+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_streaming_dag.run_streaming scheduled__2025-09-11T03:49:00+00:00 [queued]>
[2025-09-11T03:51:08.072+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_streaming_dag.run_streaming scheduled__2025-09-11T03:49:00+00:00 [queued]>
[2025-09-11T03:51:08.073+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-11T03:51:08.099+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_streaming> on 2025-09-11 03:49:00+00:00
[2025-09-11T03:51:08.107+0000] {standard_task_runner.py:57} INFO - Started process 215 to run task
[2025-09-11T03:51:08.112+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_streaming_dag', 'run_streaming', 'scheduled__2025-09-11T03:49:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/streaming_dag.py', '--cfg-path', '/tmp/tmp787qoa0t']
[2025-09-11T03:51:08.115+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask run_streaming
[2025-09-11T03:51:08.222+0000] {task_command.py:416} INFO - Running <TaskInstance: spark_streaming_dag.run_streaming scheduled__2025-09-11T03:49:00+00:00 [running]> on host 901b7d260ccd
[2025-09-11T03:51:08.651+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_streaming_dag' AIRFLOW_CTX_TASK_ID='run_streaming' AIRFLOW_CTX_EXECUTION_DATE='2025-09-11T03:49:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-11T03:49:00+00:00'
[2025-09-11T03:52:13.820+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-09-11T03:52:13.830+0000] {process_utils.py:131} INFO - Sending 15 to group 215. PIDs of all processes in the group: [216, 215]
[2025-09-11T03:52:13.832+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 215
[2025-09-11T03:52:13.835+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-11T03:52:13.841+0000] {spark_utils.py:27} ERROR - Couldn't create the spark session due to exception Task received SIGTERM signal
[2025-09-11T03:52:13.846+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-09-11T03:52:13.871+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=spark_streaming_dag, task_id=run_streaming, execution_date=20250911T034900, start_date=20250911T035108, end_date=20250911T035213
[2025-09-11T03:52:13.975+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=216, status='terminated', started='03:51:08') (216) terminated with exit code None
[2025-09-11T03:52:13.976+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=215, status='terminated', exitcode=0, started='03:51:07') (215) terminated with exit code 0
