[2025-09-11T03:52:06.297+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_streaming_dag.run_streaming scheduled__2025-09-11T03:51:00+00:00 [queued]>
[2025-09-11T03:52:06.310+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_streaming_dag.run_streaming scheduled__2025-09-11T03:51:00+00:00 [queued]>
[2025-09-11T03:52:06.310+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-11T03:52:06.329+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_streaming> on 2025-09-11 03:51:00+00:00
[2025-09-11T03:52:06.335+0000] {standard_task_runner.py:57} INFO - Started process 269 to run task
[2025-09-11T03:52:06.339+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_streaming_dag', 'run_streaming', 'scheduled__2025-09-11T03:51:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/streaming_dag.py', '--cfg-path', '/tmp/tmphv6bajnk']
[2025-09-11T03:52:06.342+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask run_streaming
[2025-09-11T03:52:06.408+0000] {task_command.py:416} INFO - Running <TaskInstance: spark_streaming_dag.run_streaming scheduled__2025-09-11T03:51:00+00:00 [running]> on host 901b7d260ccd
[2025-09-11T03:52:06.550+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_streaming_dag' AIRFLOW_CTX_TASK_ID='run_streaming' AIRFLOW_CTX_EXECUTION_DATE='2025-09-11T03:51:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-11T03:51:00+00:00'
[2025-09-11T03:52:36.513+0000] {spark_utils.py:25} INFO - Spark connection created successfully!
[2025-09-11T03:52:40.482+0000] {spark_utils.py:43} INFO - kafka dataframe created successfully
[2025-09-11T03:52:41.104+0000] {data_processing.py:49} INFO - Schema applied and JSON parsed.
[2025-09-11T03:52:41.135+0000] {data_processing.py:53} INFO - Dropped records with null id, email, or registered_date.
[2025-09-11T03:52:41.190+0000] {data_processing.py:61} INFO - Applied business rule validation.
[2025-09-11T03:52:41.206+0000] {data_processing.py:65} INFO - Deduplicated based on id.
[2025-09-11T03:52:41.231+0000] {cassandra_utils.py:15} WARNING - Cluster.__init__ called with contact_points specified, but no load_balancing_policy. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['cassandra'], lbp = None)
[2025-09-11T03:52:41.250+0000] {cassandra_utils.py:16} WARNING - Downgrading core protocol version from 66 to 65 for 172.18.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2025-09-11T03:52:41.254+0000] {cassandra_utils.py:16} WARNING - Downgrading core protocol version from 65 to 5 for 172.18.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2025-09-11T03:52:41.290+0000] {policies.py:289} INFO - Using datacenter 'datacenter1' for DCAwareRoundRobinPolicy (via host '172.18.0.4:9042'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
[2025-09-11T03:52:41.343+0000] {cassandra_utils.py:18} INFO - Connected to Cassandra!
[2025-09-11T03:52:41.362+0000] {logging_mixin.py:154} INFO - Keyspace created successfully!
[2025-09-11T03:52:41.379+0000] {logging_mixin.py:154} INFO - Table created successfully!
[2025-09-11T03:52:41.380+0000] {run_streaming.py:30} INFO - Streaming is being started...
[2025-09-11T03:53:09.770+0000] {run_streaming.py:51} ERROR - Streaming job failed: [STREAM_FAILED] Query [id = fd967fbe-1a71-40b5-9e70-cef2c713133d, runId = b2102be3-c7f9-4126-bfe7-a1e3ef96eb96] terminated with exception: Job aborted due to stage failure: Task 108 in stage 1.0 failed 1 times, most recent failure: Lost task 108.0 in stage 1.0 (TID 25) (901b7d260ccd executor driver): java.io.IOException: Failed to write statements to spark_streams.created_users. The
latest exception was
  All 1 node(s) tried for the query failed (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=cassandra/172.18.0.4:9042, hostId=0fbb740b-e6e9-46c5-9c15-59db3e9799ef, hashCode=2f16b7e4): [com.datastax.oss.driver.api.core.connection.ClosedConnectionException: Unexpected error on channel, com.datastax.oss.driver.shaded.netty.channel.StacklessClosedChannelException]

Please check the executor logs for more exceptions and information
             
	at com.datastax.spark.connector.writer.AsyncStatementWriter.$anonfun$close$2(TableWriter.scala:282)
	at scala.Option.map(Option.scala:230)
	at com.datastax.spark.connector.writer.AsyncStatementWriter.close(TableWriter.scala:277)
	at com.datastax.spark.connector.datasource.CassandraDriverDataWriter.commit(CasssandraDriverDataWriterFactory.scala:46)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.$anonfun$run$1(WriteToDataSourceV2Exec.scala:459)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1397)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.run(WriteToDataSourceV2Exec.scala:486)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.run$(WriteToDataSourceV2Exec.scala:425)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:491)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:388)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.io.IOException: Failed to write statements to spark_streams.created_users. The
latest exception was
  All 1 node(s) tried for the query failed (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=cassandra/172.18.0.4:9042, hostId=0fbb740b-e6e9-46c5-9c15-59db3e9799ef, hashCode=2f16b7e4): [com.datastax.oss.driver.api.core.connection.ClosedConnectionException: Unexpected error on channel, com.datastax.oss.driver.shaded.netty.channel.StacklessClosedChannelException]

Please check the executor logs for more exceptions and information
             
		at com.datastax.spark.connector.writer.AsyncStatementWriter.$anonfun$close$2(TableWriter.scala:282)
		at scala.Option.map(Option.scala:230)
		at com.datastax.spark.connector.writer.AsyncStatementWriter.close(TableWriter.scala:277)
		at com.datastax.spark.connector.datasource.CassandraDriverDataWriter.abort(CasssandraDriverDataWriterFactory.scala:51)
		at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.$anonfun$run$6(WriteToDataSourceV2Exec.scala:482)
		at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1408)
		... 15 more
	Suppressed: java.io.IOException: Failed to write statements to spark_streams.created_users. The
latest exception was
  All 1 node(s) tried for the query failed (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=cassandra/172.18.0.4:9042, hostId=0fbb740b-e6e9-46c5-9c15-59db3e9799ef, hashCode=2f16b7e4): [com.datastax.oss.driver.api.core.connection.ClosedConnectionException: Unexpected error on channel, com.datastax.oss.driver.shaded.netty.channel.StacklessClosedChannelException]

Please check the executor logs for more exceptions and information
             
		at com.datastax.spark.connector.writer.AsyncStatementWriter.$anonfun$close$2(TableWriter.scala:282)
		at scala.Option.map(Option.scala:230)
		at com.datastax.spark.connector.writer.AsyncStatementWriter.close(TableWriter.scala:277)
		at com.datastax.spark.connector.datasource.CassandraDriverDataWriter.close(CasssandraDriverDataWriterFactory.scala:56)
		at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.$anonfun$run$9(WriteToDataSourceV2Exec.scala:486)
		at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1419)
		... 15 more

Driver stacktrace:
Traceback (most recent call last):
  File "/opt/airflow/dags/spark_job/run_streaming.py", line 45, in run_streaming
    streaming_query.awaitTermination(30)
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/sql/streaming/query.py", line 219, in awaitTermination
    return self._jsq.awaitTermination(int(timeout * 1000))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = fd967fbe-1a71-40b5-9e70-cef2c713133d, runId = b2102be3-c7f9-4126-bfe7-a1e3ef96eb96] terminated with exception: Job aborted due to stage failure: Task 108 in stage 1.0 failed 1 times, most recent failure: Lost task 108.0 in stage 1.0 (TID 25) (901b7d260ccd executor driver): java.io.IOException: Failed to write statements to spark_streams.created_users. The
latest exception was
  All 1 node(s) tried for the query failed (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=cassandra/172.18.0.4:9042, hostId=0fbb740b-e6e9-46c5-9c15-59db3e9799ef, hashCode=2f16b7e4): [com.datastax.oss.driver.api.core.connection.ClosedConnectionException: Unexpected error on channel, com.datastax.oss.driver.shaded.netty.channel.StacklessClosedChannelException]

Please check the executor logs for more exceptions and information
             
	at com.datastax.spark.connector.writer.AsyncStatementWriter.$anonfun$close$2(TableWriter.scala:282)
	at scala.Option.map(Option.scala:230)
	at com.datastax.spark.connector.writer.AsyncStatementWriter.close(TableWriter.scala:277)
	at com.datastax.spark.connector.datasource.CassandraDriverDataWriter.commit(CasssandraDriverDataWriterFactory.scala:46)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.$anonfun$run$1(WriteToDataSourceV2Exec.scala:459)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1397)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.run(WriteToDataSourceV2Exec.scala:486)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.run$(WriteToDataSourceV2Exec.scala:425)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:491)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:388)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.io.IOException: Failed to write statements to spark_streams.created_users. The
latest exception was
  All 1 node(s) tried for the query failed (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=cassandra/172.18.0.4:9042, hostId=0fbb740b-e6e9-46c5-9c15-59db3e9799ef, hashCode=2f16b7e4): [com.datastax.oss.driver.api.core.connection.ClosedConnectionException: Unexpected error on channel, com.datastax.oss.driver.shaded.netty.channel.StacklessClosedChannelException]

Please check the executor logs for more exceptions and information
             
		at com.datastax.spark.connector.writer.AsyncStatementWriter.$anonfun$close$2(TableWriter.scala:282)
		at scala.Option.map(Option.scala:230)
		at com.datastax.spark.connector.writer.AsyncStatementWriter.close(TableWriter.scala:277)
		at com.datastax.spark.connector.datasource.CassandraDriverDataWriter.abort(CasssandraDriverDataWriterFactory.scala:51)
		at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.$anonfun$run$6(WriteToDataSourceV2Exec.scala:482)
		at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1408)
		... 15 more
	Suppressed: java.io.IOException: Failed to write statements to spark_streams.created_users. The
latest exception was
  All 1 node(s) tried for the query failed (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=cassandra/172.18.0.4:9042, hostId=0fbb740b-e6e9-46c5-9c15-59db3e9799ef, hashCode=2f16b7e4): [com.datastax.oss.driver.api.core.connection.ClosedConnectionException: Unexpected error on channel, com.datastax.oss.driver.shaded.netty.channel.StacklessClosedChannelException]

Please check the executor logs for more exceptions and information
             
		at com.datastax.spark.connector.writer.AsyncStatementWriter.$anonfun$close$2(TableWriter.scala:282)
		at scala.Option.map(Option.scala:230)
		at com.datastax.spark.connector.writer.AsyncStatementWriter.close(TableWriter.scala:277)
		at com.datastax.spark.connector.datasource.CassandraDriverDataWriter.close(CasssandraDriverDataWriterFactory.scala:56)
		at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.$anonfun$run$9(WriteToDataSourceV2Exec.scala:486)
		at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1419)
		... 15 more

Driver stacktrace:
[2025-09-11T03:53:09.860+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-09-11T03:53:09.893+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=spark_streaming_dag, task_id=run_streaming, execution_date=20250911T035100, start_date=20250911T035206, end_date=20250911T035309
[2025-09-11T03:53:09.965+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-11T03:53:10.020+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
